from sqlalchemy import text, String, Integer, DateTime, Index
from sqlalchemy.orm import DeclarativeBase, mapped_column, Mapped
from datetime import datetime
from backend.database import Base


class BidNotice(Base):
    __tablename__: Mapped[str] = 'bid_notice'
    # __table_args__ = (
    #     Index()
    # )

    apl_bss_cntnts: Mapped[str] = mapped_column(String(30), comment='적용기준내용')
    arslt_appl_doc_rcpt_dt: Mapped[str] = mapped_column(String(19), comment='실적신청서접수일시')
    arslt_appl_doc_rcpt_mthd_nm: Mapped[str] = mapped_column(String(50), comment='실적신청서접수방법명')
    arslt_cmpt_yn: Mapped[str] = mapped_column(String(1), comment='실적경쟁여부')
    bdgt_amt: Mapped[str] = mapped_column(String(25), comment='예산금액')
    bf_spec_rgst_no: Mapped[str] = mapped_column(String(10), comment='사전규격등록번호')
    bid_begin_dt: Mapped[str] = mapped_column(String(19), comment='입찰개시일시')
    bid_clse_dt: Mapped[str] = mapped_column(String(19), comment='입찰마감일시')
    bid_grntymny_paymnt_yn: Mapped[str] = mapped_column(String(30), comment='입찰보증금납부여부')
    bid_methd_nm: Mapped[str] = mapped_column(String(200), comment='입찰방식명')
    bid_ntce_dt: Mapped[str] = mapped_column(String(19), comment='입찰공고일시')
    bid_ntce_dtl_url: Mapped[str] = mapped_column(String(512), comment='입찰공고상세URL')
    bid_ntce_nm: Mapped[str] = mapped_column(String(100), comment='입찰공고명')
    bid_ntce_no: Mapped[str] = mapped_column(String(40), comment='입찰공고번호', primary_key=True, autoincrement=True)
    bid_ntce_ord: Mapped[str] = mapped_column(String(3), comment='입찰공고차수')
    bid_ntce_url: Mapped[str] = mapped_column(String(500), comment='입찰공고URL')
    bid_prtcpt_fee: Mapped[str] = mapped_column(String(21), comment='입찰참가수수료')
    bid_prtcpt_fee_paymnt_yn: Mapped[str] = mapped_column(String(30), comment='입찰참가수수료납부여부')
    bid_prtcpt_lmt_yn: Mapped[str] = mapped_column(String(1), comment='입찰참가제한여부')
    bid_qlfct_rgst_dt: Mapped[str] = mapped_column(String(19), comment='입찰참가자격등록마감일시')
    bid_wgrntee_rcpt_clse_dt: Mapped[str] = mapped_column(String(19), comment='입찰보증서접수마감일시')
    brffc_bidprc_permsn_yn: Mapped[str] = mapped_column(String(1), comment='지사투찰허용여부')
    chg_dt: Mapped[str] = mapped_column(String(19), comment='변경일시')
    chg_ntce_rsn: Mapped[str] = mapped_column(String(4000), comment='변경공고사유')
    cibl_apl_yn: Mapped[str] = mapped_column(String(1), comment='건설산업법적용대상여부')
    cmmn_spldmd_agrmnt_clse_dt: Mapped[str] = mapped_column(String(19), comment='공동수급협정마감일시')
    cmmn_spldmd_agrmnt_rcptdoc_methd: Mapped[str] = mapped_column(String(30), comment='공동수급협정서접수방식')
    cmmn_spldmd_cnum: Mapped[str] = mapped_column(String(100), comment='공동수급업체수')
    cmmn_spldmd_corp_rgn_lmt_yn: Mapped[str] = mapped_column(String(1), comment='공동수급업체지역제한여부')
    cmmn_spldmd_methd_cd: Mapped[str] = mapped_column(String(15), comment='공동수급방식코드')
    cmmn_spldmd_methd_nm: Mapped[str] = mapped_column(String(100), comment='공동수급방식명')
    cnstrtn_ablty_evl_amt_list: Mapped[str] = mapped_column(String(4000), comment='시공능력평가금액목록')
    cnstrtsite_rgn_nm: Mapped[str] = mapped_column(String(256), comment='공사현장지역명')
    cnstty_accot_shre_rate_list: Mapped[str] = mapped_column(String(4000), comment='공종별지분율목록')
    cntrct_cncls_mthd_nm: Mapped[str] = mapped_column(String(200), comment='계약체결방법명')
    contrctrcnstrtn_govsply_mtrl_amt: Mapped[str] = mapped_column(String(21), comment='도급자설치관급자재금액')
    crdtr_nm: Mapped[str] = mapped_column(String(200), comment='채권자명')
    dcmtg_oprtn_dt: Mapped[str] = mapped_column(String(19), comment='설명회실시일시')
    dcmtg_oprtn_plce: Mapped[str] = mapped_column(String(100), comment='설명회실시장소')
    dminstt_cd: Mapped[str] = mapped_column(String(7), comment='수요기관코드')
    dminstt_nm: Mapped[str] = mapped_column(String(200), comment='수요기관명')
    dminstt_ofcl_email_adrs: Mapped[str] = mapped_column(String(100), comment='수요기관담당자이메일주소')
    drwt_prdprc_num: Mapped[str] = mapped_column(String(20), comment='추첨예가건수')
    dsgnt_cmpt_yn: Mapped[str] = mapped_column(String(1), comment='지명경쟁여부')
    dtls_bid_yn: Mapped[str] = mapped_column(String(1), comment='내역입찰여부')
    exctv_nm: Mapped[str] = mapped_column(String(35), comment='집행관명')
    govcnstrtn_govsply_mtrl_amt: Mapped[str] = mapped_column(String(21), comment='관급자설치관급자재금액')
    govsply_amt: Mapped[str] = mapped_column(String(21), comment='관급금액')
    incntv_rgn_nm1: Mapped[str] = mapped_column(String(200), comment='가산지역명1')
    incntv_rgn_nm2: Mapped[str] = mapped_column(String(200), comment='가산지역명2')
    incntv_rgn_nm3: Mapped[str] = mapped_column(String(200), comment='가산지역명3')
    incntv_rgn_nm4: Mapped[str] = mapped_column(String(200), comment='가산지역명4')
    indstryty_evl_rt: Mapped[str] = mapped_column(String(20), comment='업종평가비율')
    indstryty_lmt_yn: Mapped[str] = mapped_column(String(1), comment='업종제한여부')
    indstryty_mfrc_fld_evl_yn: Mapped[str] = mapped_column(String(1), comment='주력분야평가여부')
    induty_vat: Mapped[str] = mapped_column(String(25), comment='주공종부가가치세')
    intrbid_yn: Mapped[str] = mapped_column(String(1), comment='국제입찰여부')
    jntcontrct_duty_rgn_nm1: Mapped[str] = mapped_column(String(200), comment='공동도급의무지역명1')
    jntcontrct_duty_rgn_nm2: Mapped[str] = mapped_column(String(200), comment='공동도급의무지역명2')
    jntcontrct_duty_rgn_nm3: Mapped[str] = mapped_column(String(200), comment='공동도급의무지역명3')
    main_cnstty_cnstwk_prearng_amt: Mapped[str] = mapped_column(String(21), comment='주공종공사예정금액')
    main_cnstty_nm: Mapped[str] = mapped_column(String(200), comment='주공종명')
    main_cnstty_presmpt_prce: Mapped[str] = mapped_column(String(25), comment='주공종추정가격')
    mtlty_advc_psbl_yn: Mapped[str] = mapped_column(String(1), comment='상호시장진출허용여부')
    mtlty_advc_psbl_yn_cnstwk_nm: Mapped[str] = mapped_column(String(100), comment='건설산업법적용대상공사명')
    ntce_dscrpt_yn: Mapped[str] = mapped_column(String(1), comment='공고설명여부')
    ntce_instt_cd: Mapped[str] = mapped_column(String(7), comment='공고기관코드')
    ntce_instt_nm: Mapped[str] = mapped_column(String(200), comment='공고기관명')
    ntce_instt_ofcl_email_adrs: Mapped[str] = mapped_column(String(100), comment='공고기관담당자이메일주소')
    ntce_instt_ofcl_nm: Mapped[str] = mapped_column(String(35), comment='공고기관담당자명')
    ntce_instt_ofcl_tel_no: Mapped[str] = mapped_column(String(25), comment='공고기관담당자전화번호')
    ntce_kind_nm: Mapped[str] = mapped_column(String(100), comment='공고종류명')
    ntce_spec_doc_url1: Mapped[str] = mapped_column(String(800), comment='공고규격서URL1')
    ntce_spec_doc_url10: Mapped[str] = mapped_column(String(800), comment='공고규격서URL10')
    ntce_spec_doc_url2: Mapped[str] = mapped_column(String(800), comment='공고규격서URL2')
    ntce_spec_doc_url3: Mapped[str] = mapped_column(String(800), comment='공고규격서URL3')
    ntce_spec_doc_url4: Mapped[str] = mapped_column(String(800), comment='공고규격서URL4')
    ntce_spec_doc_url5: Mapped[str] = mapped_column(String(800), comment='공고규격서URL5')
    ntce_spec_doc_url6: Mapped[str] = mapped_column(String(800), comment='공고규격서URL6')
    ntce_spec_doc_url7: Mapped[str] = mapped_column(String(800), comment='공고규격서URL7')
    ntce_spec_doc_url8: Mapped[str] = mapped_column(String(800), comment='공고규격서URL8')
    ntce_spec_doc_url9: Mapped[str] = mapped_column(String(800), comment='공고규격서URL9')
    ntce_spec_file_nm1: Mapped[str] = mapped_column(String(256), comment='공고규격파일명1')
    ntce_spec_file_nm10: Mapped[str] = mapped_column(String(256), comment='공고규격파일명10')
    ntce_spec_file_nm2: Mapped[str] = mapped_column(String(256), comment='공고규격파일명2')
    ntce_spec_file_nm3: Mapped[str] = mapped_column(String(256), comment='공고규격파일명3')
    ntce_spec_file_nm4: Mapped[str] = mapped_column(String(256), comment='공고규격파일명4')
    ntce_spec_file_nm5: Mapped[str] = mapped_column(String(256), comment='공고규격파일명5')
    ntce_spec_file_nm6: Mapped[str] = mapped_column(String(256), comment='공고규격파일명6')
    ntce_spec_file_nm7: Mapped[str] = mapped_column(String(256), comment='공고규격파일명7')
    ntce_spec_file_nm8: Mapped[str] = mapped_column(String(256), comment='공고규격파일명8')
    ntce_spec_file_nm9: Mapped[str] = mapped_column(String(256), comment='공고규격파일명9')
    openg_dt: Mapped[str] = mapped_column(String(19), comment='개찰일시')
    openg_plce: Mapped[str] = mapped_column(String(100), comment='개찰장소')
    order_plan_unty_no: Mapped[str] = mapped_column(String(35), comment='발주계획통합번호')
    pq_appl_doc_rcpt_dt: Mapped[str] = mapped_column(String(19), comment='PQ신청서접수일시')
    pq_appl_doc_rcpt_mthd_nm: Mapped[str] = mapped_column(String(30), comment='PQ신청서접수방법명')
    pq_eval_yn: Mapped[str] = mapped_column(String(1), comment='PQ심사여부')
    prearng_prce_dcsn_mthd_nm: Mapped[str] = mapped_column(String(20), comment='예정가격결정방법명')
    presmpt_prce: Mapped[str] = mapped_column(String(25), comment='추정가격')
    rbid_openg_dt: Mapped[str] = mapped_column(String(19), comment='재입찰개찰일시')
    rbid_permsn_yn: Mapped[str] = mapped_column(String(1), comment='재입찰허용여부')
    re_ntce_yn: Mapped[str] = mapped_column(String(1), comment='재공고여부')
    ref_no: Mapped[str] = mapped_column(String(105), comment='참조번호')
    rgn_duty_jntcontrct_rt: Mapped[str] = mapped_column(String(20), comment='지역의무공동도급비율')
    rgn_duty_jntcontrct_yn: Mapped[str] = mapped_column(String(1), comment='지역의무공동도급여부')
    rgst_dt: Mapped[str] = mapped_column(String(19), comment='등록일시')
    rgst_ty_nm: Mapped[str] = mapped_column(String(100), comment='등록유형명')
    rsrvtn_prce_re_mkng_mthd_nm: Mapped[str] = mapped_column(String(50), comment='예비가격재작성방법명')
    spt_dscrpt_doc_url1: Mapped[str] = mapped_column(String(500), comment='현장설명서URL1')
    spt_dscrpt_doc_url2: Mapped[str] = mapped_column(String(500), comment='현장설명서URL2')
    spt_dscrpt_doc_url3: Mapped[str] = mapped_column(String(500), comment='현장설명서URL3')
    spt_dscrpt_doc_url4: Mapped[str] = mapped_column(String(500), comment='현장설명서URL4')
    spt_dscrpt_doc_url5: Mapped[str] = mapped_column(String(500), comment='현장설명서URL5')
    std_ntce_doc_url: Mapped[str] = mapped_column(String(256), comment='표준공고서URL')
    status: Mapped[int] = mapped_column(Integer, comment='상태값')
    subsi_cnstty_indstryty_evl_rt1: Mapped[str] = mapped_column(String(20), comment='부공종업종평가비율1')
    subsi_cnstty_indstryty_evl_rt2: Mapped[str] = mapped_column(String(20), comment='부공종업종평가비율2')
    subsi_cnstty_indstryty_evl_rt3: Mapped[str] = mapped_column(String(20), comment='부공종업종평가비율3')
    subsi_cnstty_indstryty_evl_rt4: Mapped[str] = mapped_column(String(20), comment='부공종업종평가비율4')
    subsi_cnstty_indstryty_evl_rt5: Mapped[str] = mapped_column(String(20), comment='부공종업종평가비율5')
    subsi_cnstty_indstryty_evl_rt6: Mapped[str] = mapped_column(String(20), comment='부공종업종평가비율6')
    subsi_cnstty_indstryty_evl_rt7: Mapped[str] = mapped_column(String(20), comment='부공종업종평가비율7')
    subsi_cnstty_indstryty_evl_rt8: Mapped[str] = mapped_column(String(20), comment='부공종업종평가비율8')
    subsi_cnstty_indstryty_evl_rt9: Mapped[str] = mapped_column(String(20), comment='부공종업종평가비율9')
    subsi_cnstty_nm1: Mapped[str] = mapped_column(String(200), comment='부대공종명1')
    subsi_cnstty_nm2: Mapped[str] = mapped_column(String(200), comment='부대공종명2')
    subsi_cnstty_nm3: Mapped[str] = mapped_column(String(200), comment='부대공종명3')
    subsi_cnstty_nm4: Mapped[str] = mapped_column(String(200), comment='부대공종명4')
    subsi_cnstty_nm5: Mapped[str] = mapped_column(String(200), comment='부대공종명5')
    subsi_cnstty_nm6: Mapped[str] = mapped_column(String(200), comment='부대공종명6')
    subsi_cnstty_nm7: Mapped[str] = mapped_column(String(200), comment='부대공종명7')
    subsi_cnstty_nm8: Mapped[str] = mapped_column(String(200), comment='부대공종명8')
    subsi_cnstty_nm9: Mapped[str] = mapped_column(String(200), comment='부대공종명9')
    sucsfbid_lwlt_rate: Mapped[str] = mapped_column(String(22), comment='낙찰하한율')
    sucsfbid_mthd_cd: Mapped[str] = mapped_column(String(9), comment='낙찰방법코드')
    sucsfbid_mthd_nm: Mapped[str] = mapped_column(String(200), comment='낙찰방법명')
    tot_prdprc_num: Mapped[str] = mapped_column(String(20), comment='총예가건수')
    unty_ntce_no: Mapped[str] = mapped_column(String(11), comment='통합공고번호')
    vat: Mapped[str] = mapped_column(String(25), comment='부가가치세')
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=text('CURRENT_TIMESTAMP'), comment='최초 생성 시간')
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=text('CURRENT_TIMESTAMP'), comment='최종 수정 시간')
